### ISSUE TITLE
Any plans for adding type definitions? (typescript)

### ISSUE THREAD

**Issue by jorgerodrigues** [torchlight-api/remark-torchlight#3]

**Comment by aarondfrancis** [comment]
No, probably not. I'm not familiar enough with TypeScript.

**Comment by dominiccarrington** [comment]
Hi,
I have just created a pull request on Definitely Typed to add types for this package.

Currently, I've got the types for @torchlight-api/torchlight-cli pending: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68652
And then will create the pull request for this package, since this is a dependant.
